FROM node:20

WORKDIR /app

COPY package.json .
COPY yarn.lock .
COPY ./dist ./dist
COPY ./config ./config
COPY ./.env ./.env

RUN yarn global add @nestjs/cli
RUN yarn install --production

EXPOSE 4000
ENV NODE_ENV=staging

CMD ["yarn", "start:staging"]