export enum RedisKeys {
  AccountingProducts = 'accounting-products',
  AccountingStocks = 'accounting-stocks',
  MenuItems = 'menu-items',
  MenuCategories = 'menu-categories',
  ActiveMenuCategories = 'active-menu-categories',
  Discounts = 'discounts',
  Pages = 'pages',
  IkasToken = 'ikas-token',
  Users = 'users',
  MinimalUsers = 'minimal-users',
  Authorizations = 'authorizations',
  PopularDiscounts = 'popular-discounts',
  Shifts = 'shifts',
  Kitchens = 'kitchens',
  Locations = 'locations',
  AllLocations = 'all-locations',
  Memberships = 'memberships',
  GamesMinimal = 'games-minimal',
  Tables = 'tables',
}
